sudo: required
services:
  - docker
# build only the client image
before_install:
  - docker build -t sampalm/docker-react -f ./client/Dockerfile.dev ./client
# make a simple test of the client image
script:
  - docker run sampalm/docker-react npm test -- --coverage
# build multi-container images
after_success:
  - docker build -t sampalm/dr-client ./client
  - docker build -t sampalm/dr-nginx ./nginx
  - docker build -t sampalm/dr-server ./server
  - docker build -t sampalm/dr-worker ./worker
  # login in to the docker cli
  - echo "$DOCKER_PASS" | docker login -u "$DOCKER_ID" --password-stdin
  ## Push images to docker hub
  - docker push sampalm/dr-client
  - docker push sampalm/dr-nginx
  - docker push sampalm/dr-server
  - docker push sampalm/dr-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-487676984512
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY